SmartLMS.WebUI/Models/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;
using SmartLMS.Domain.Resources;

namespace SmartLMS.WebUI.Models
{
    public class ChangePasswordViewModel
    {
        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "UserPasswordRequired")]
        [UIHint("Password")]
        public string Password { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resource),
            ErrorMessageResourceName = "PasswordConfirmationRequired")]
        [UIHint("Password")]
        [Compare("Password", ErrorMessageResourceType = typeof(Resource),
            ErrorMessageResourceName = "PasswordDoenstMatch")]
        public string ConfirmPassword { get; set; }
    }
}

SmartLMS.WebUI/Models/ForgotPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SmartLMS.WebUI.Models
{
    public class ForgotPasswordViewModel
    {
        [Required] public string Email { get; set; }
    }
}

SmartLMS.WebUI/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SmartLMS.WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Login { get; set; }

        [Required] [UIHint("Password")] public string Password { get; set; }

        public bool RememberMe { get; set; }
    }
}

SmartLMS.WebUI/Controllers/AuthenticationController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Security;
using Carubbi.Mailer.Implementation;
using SmartLMS.Domain;
using SmartLMS.Domain.Entities.UserAccess;
using SmartLMS.Domain.Resources;
using SmartLMS.Domain.Services;
using SmartLMS.WebUI.Models;

namespace SmartLMS.WebUI.Controllers
{
    [AllowAnonymous]
    public class AuthenticationController : BaseController
    {
        public AuthenticationController(IContext context)
            : base(context)
        {
        }

        // GET: Autenticacao
        public ActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return Json(
                    new
                    {
                        ValidationSummary = RenderRazorViewToString("_ValidationErrors", viewModel),
                        Authenticated = false
                    }, JsonRequestBehavior.AllowGet);


            var authenticationService = new AuthenticationService(_context, new SmtpSender());
            if (authenticationService.Login(viewModel.Login, viewModel.Password))
            {
                FormsAuthentication.SetAuthCookie(viewModel.Login, viewModel.RememberMe);
                var url = FormsAuthentication.GetRedirectUrl(viewModel.Login, viewModel.RememberMe);
                return Json(new {Url = url, Authenticated = true}, JsonRequestBehavior.AllowGet);
            }

            ModelState.AddModelError("IvalidUserOrPassword", "Invalid User or password");

            return Json(
                new
                {
                    ValidationSummary = RenderRazorViewToString("_ValidationErrors", viewModel),
                    Authenticated = false
                }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ForgotPassword()
        {
            var viewModel = new ForgotPasswordViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);
            var sender = new SmtpSender();
            var authenticationService = new AuthenticationService(_context, sender);
            var password = authenticationService.RecoverPassword(viewModel.Email);
            if (password != null)
            {
                var notificationService = new NotificationService(_context, sender);
                await Task.Run(() => notificationService.SendRecoverPasswordNotification(viewModel.Email, password))
                    .ConfigureAwait(false);
                ViewBag.Message = "We sent an e-mail to you with your password.";
            }
            else
            {
                ViewBag.Message = "";
                ModelState.AddModelError("EmailNaoEncontrado", "E-mail not found");
            }

            return View(viewModel);
        }

        [Authorize]
        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult ChangePassword()
        {
            var viewModel = new ChangePasswordViewModel();
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            if (!ModelState.IsValid) return View(changePasswordViewModel);

            var authenticationService = new AuthenticationService(_context, new SmtpSender());
            authenticationService.UpdatedUser(_loggedUser.Id,
                _loggedUser.Name,
                _loggedUser.Email,
                _loggedUser.Login,
                changePasswordViewModel.Password,
                _loggedUser.Active,
                (Role) Enum.Parse(typeof(Role),
                    _context.UnProxy(_loggedUser).GetType().Name),
                _loggedUser);

            TempData["MessageType"] = "success";
            TempData["MessageTitle"] = Resource.NotificationToastrTitle;
            TempData["Message"] = Resource.PasswordUpdatedToastrMessage;

            return RedirectToAction("Index", "Home");
        }
    }
}

SmartLMS.WebUI/Views/Authentication/ChangePassword.cshtml
@using SmartLMS.Domain.Resources
@model ChangePasswordViewModel

@{
    ViewBag.Title = Resource.ChangePasswordPageTitle;
}

<div class="col-md-offset-2 col-md-8">
    <div class="card">
        <div class="content">
            <h2 class="text-primary index-title">@Resource.ChangePasswordPageTitle</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>@Resource.ChangePasswordInformation</h4>

                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})


                    <div class="form-group label-floating">
                        <div class="col-md-offset-2 col-md-8">
                            <label class="control-label">@Resource.NewPasswordLabel</label>
                            @Html.EditorFor(model => model.Password, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.Password, "", new {@class = "text-danger"})
                        </div>
                    </div>


                    <div class="form-group label-floating">
                        <div class="col-md-offset-2 col-md-8">
                            <label class="control-label">@Resource.ConfirmPasswordLabel</label>
                            @Html.EditorFor(model => model.ConfirmPassword, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new {@class = "text-danger"})
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="@Resource.SendButton" class="btn btn-primary"/>
                            @Html.ActionLink(Resource.BackToHome, "Index", "Home", null, new {@class = "btn btn-default"})
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SmartLMS.WebUI/Views/Authentication/ForgotPassword.cshtml
@using SmartLMS.Domain.Resources
@model ForgotPasswordViewModel

@{
    ViewBag.Title = Resource.ForgotPasswordTitle;
    Layout = "~/Views/Authentication/_Layout.cshtml";
}


<div class="panel panel-primary card-signup">
    <div class="panel-heading">
        <div class="text-center panel-title">@Resource.ForgotPasswordTitle</div>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                @using (Html.BeginForm("ForgotPassword", "Authentication", FormMethod.Post))
                {
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">email</i>
                        </span>
                        <div class="form-group label-floating">
                            <label class="control-label">@Resource.ForgotPasswordLoginLabel</label>
                            @Html.TextBoxFor(x => x.Email, new {@class = "form-control"})
                        </div>
                    </div>
                    <div>
                        @Html.ValidationSummary(false, "", new {@class = "alert alert-danger text-danger"})
                        @if (!string.IsNullOrEmpty(ViewBag.Message))
                        {
                            <div class="alert alert-success">
                                @ViewBag.Message
                            </div>
                        }
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <button name="login-submit" id="login-submit" class="btn btn-simple btn-primary">@Resource.SendButton</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="text-center">
                                @Html.ActionLink(Resource.BackToLogin, "Login", null, new {@class = "btn btn-simple forgot-password"})
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SmartLMS.WebUI/Views/Authentication/Login.cshtml
@using SmartLMS.Domain.Entities
@using SmartLMS.Domain.Resources
@model LoginViewModel
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Authentication/_Layout.cshtml";
}


<div class="card card-signup">

    @using (Html.BeginForm("Login", "Authentication",
        new {ReturnUrl = Request.QueryString["ReturnUrl"]},
        FormMethod.Post,
        new {@class = "form", id = "login-form"}))
    {
        @Html.AntiForgeryToken()

        <div class="header header-primary text-center">
            <h2>@Parameter.APP_NAME</h2>
            <h4>Powered by Smart LMS</h4>
        </div>
        <div class="content">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">email</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">@Resource.LoginEmailLabel</label>
                    @Html.TextBoxFor(x => x.Login, new {@class = "form-control", id = "login-textbox"})
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">lock_outline</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">@Resource.LoginPasswordLabel</label>
                    @Html.EditorFor(x => x.Password, new {HtmlAttributes = new {id = "password-textbox"}})
                </div>
            </div>
            <div class="togglebutton text-center">
                <label>
                    @Html.CheckBoxFor(x => x.RememberMe, new {name = "remember", id = "remember"})
                    @Resource.RememberMeLabel
                </label>
            </div>


        </div>
        <div class="footer text-center">
            <button name="login-submit" id="login-submit" class="btn btn-simple btn-primary btn-lg">Login</button>
        </div>
        <div class="footer text-center">
            @Html.ActionLink(Resource.BackToHome, "Index", "Home", null, new {@class = "btn btn-simple btn-primary"})
        </div>
        <div id="ValidationSummaryContainer" class="container">

        </div>

        <div class="text-center">
            @Html.ActionLink(Resource.ForgotPasswordButton, "ForgotPassword", null, new {@class = "btn btn-simple forgot-password"})
        </div>
    }
</div>
<div id="pre-loader-loading"></div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>


        (function() {
            var $private = {};

            $(function() {
                $("#login-form").on("submit", $private.Authenticate);
            });

            $private.Authenticate = function(e) {
                e.preventDefault();
                $.validator.unobtrusive.parse($(this));

                if ($(this).valid()) {
                    var sendOriginalText = $("#login-submit").text();
                    var sending =
                        $(
                            "<img src='@Url.Content("~/Content/img/loading-green.gif")' style='width:18px'> <span>@Resource.Authenticating</span>");
                    $("#login-submit").html(sending);
                    $("#login-submit").prop('disabled', true);
                    $.ajax({
                        url: this.action,
                        type: this.method,
                        data: $(this).serialize(),
                        success: function(result) {
                            if (result.Authenticated)
                                document.location.href = result.Url;
                            else {
                                $("#login-textbox").val("");
                                $("#password-textbox").val("");
                                $("#login-submit").text(sendOriginalText);
                                $("#login-submit").prop('disabled', false);
                                $("#ValidationSummaryContainer").html(result.ValidationSummary);
                            }
                        }
                    });
                }
            };
        }());
    </script>
}

SmartLMS.WebUI/Views/Authentication/_Layout.cshtml
@using SmartLMS.Domain.Entities
@using SmartLMS.Domain.Resources
@{
    Layout = null;

    var wallpapers = Resource.Wallpaper.Split('|');
    var rnd = new Random();
    var wallpaperIndex = rnd.Next(0, wallpapers.Length);
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>@Parameter.APP_NAME - Login</title>
    <meta http-equiv="x-ua-compatible" content="IE=10">
    <script>
        var SmartLMS = {};
        SmartLMS.api = '@Url.Content("~/")';
    </script>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/csscustom")
 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/icons/favicon-16x16.png">
    <link rel="manifest" href="~/Content/icons/site.webmanifest">
    <link rel="mask-icon" href="~/Content/icons/safari-pinned-tab.svg" color="#7f1887">
    <meta name="msapplication-TileColor" content="#7f1887">
    <meta name="theme-color" content="#7f1887">
 
</head>
<body class="signup-page">
<div class="wrapper">
    <div class="header header-filter" style="background-image: url('@wallpapers[wallpaperIndex]'); background-position: top center; background-size: cover;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-lg-4 col-lg-offset-4">
                    @RenderBody()
                </div>
            </div>

            <footer class="footer">
                <div class="container">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                Smart 2.0 - LMS
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright pull-right">
                        © 2016, @Resource.MadeWithLoveMessage <i class="fa fa-heart heart"></i> @Resource.MadeBy <a href="http://www.github.com/rcarubbi" target="_blank">Raphael Carubbi</a>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/data")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>