SmartLMS.WebUI/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SmartLMS.WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Login { get; set; }

        [Required] [UIHint("Password")] public string Password { get; set; }

        public bool RememberMe { get; set; }
    }
}

SmartLMS.WebUI/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Transactions;
using System.Web.Mvc;
using Carubbi.Extensions;
using Carubbi.Mailer.Implementation;
using Humanizer.DateTimeHumanizeStrategy;
using SmartLMS.Domain;
using SmartLMS.Domain.Entities;
using SmartLMS.Domain.Entities.Content;
using SmartLMS.Domain.Entities.Delivery;
using SmartLMS.Domain.Entities.History;
using SmartLMS.Domain.Entities.UserAccess;
using SmartLMS.Domain.Repositories;
using SmartLMS.Domain.Resources;
using SmartLMS.WebUI.Models;

namespace SmartLMS.WebUI.Controllers
{
    [Authorize]
    public class ClassController : BaseController
    {
        public ClassController(IContext context)
            : base(context)
        {
        }

        [HttpPost]
        public ActionResult UpdateProgress(ClassAccessViewModel viewModel)
        {
            var classAccessRepository = new ClassAccessRepository(_context);
            var classRepository = new ClassRepository(_context);
            var classInfo = classRepository.GetClass(viewModel.ClassId, _loggedUser.Id, GetUserRole(_loggedUser));
            classAccessRepository.UpdateProgress(viewModel.ToEntity(_loggedUser, classInfo.Class));

            return new HttpStatusCodeResult(HttpStatusCode.OK, "Updated");
        }

        public ActionResult Watch(Guid id)
        {
            var classRepository = new ClassRepository(_context);
            var classAccessRepository = new ClassAccessRepository(_context);
            var classInfo = classRepository.GetClass(id, _loggedUser.Id, GetUserRole(_loggedUser));

            if (classInfo.Available && classInfo.Class.Active)
            {
                if (GetUserRole(_loggedUser) == Role.Student)
                    classAccessRepository.CreateAccess(new ClassAccess
                    {
                        Class = classInfo.Class,
                        User = _loggedUser,
                        AccessDateTime = DateTime.Now,
                        Percentual = classInfo.Percentual,
                        WatchedSeconds = classInfo.WatchedSeconds
                    });

                return View(ClassViewModel.FromEntityWithFiles(classInfo));
            }

            TempData["MessageType"] = "warning";
            TempData["MessageTitle"] = Resource.WarningToastrTitle;
            TempData["Message"] = Resource.NotAllowedWatchClassToastrMessage;
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult Index(Guid id)
        {
            var courseRepository = new CourseRepository(_context);
            var courseIndex = courseRepository.GetCourseIndex(id, _loggedUser?.Id, GetUserRole(_loggedUser));

            if (!courseIndex.Course.Active)
            {
                TempData["MessageType"] = "warning";
                TempData["MessageTitle"] = Resource.WarningToastrTitle;
                TempData["Message"] = Resource.CourseNotAvailableToastrMessage;
                return RedirectToAction("Index", "Home");
            }

            var viewModel = CourseViewModel.FromEntity(courseIndex);

            ViewBag.OtherCourses = new SelectList(courseIndex.Course.Subject.Courses
                .Where(c => c.Active)
                .Except(new List<Course> {courseIndex.Course}), "Id", "Name");

            return View(viewModel);
        }

        [AllowAnonymous]
        public ActionResult CoursePanel(Guid id)
        {
            var courseRepository = new CourseRepository(_context);
            var courseIndex = courseRepository.GetCourseIndex(id, _loggedUser?.Id, GetUserRole(_loggedUser));
            var viewModel = CourseViewModel.FromEntity(courseIndex);
            return PartialView("_CoursePanel", viewModel);
        }

        [ChildActionOnly]
        public ActionResult ClassListSmall(Guid id, Guid currentClassId)
        {
            var courseRepository = new CourseRepository(_context);
            var courseIndex = courseRepository.GetCourseIndex(id, _loggedUser.Id, GetUserRole(_loggedUser));
            var viewModel = CourseViewModel.FromEntity(courseIndex);
            ViewBag.CurrentClassId = currentClassId;
            return PartialView("_ClassListSmall", viewModel.Classes);
        }


        [ChildActionOnly]
        public ActionResult NewClassesPanel()
        {
            var classRepository = new ClassRepository(_context);
            return PartialView("_NewClassesPanel",
                ClassViewModel.FromEntityList(classRepository.ListLastDeliveredClasses(_loggedUser.Id),
                    new DefaultDateTimeHumanizeStrategy()));
        }

        [ChildActionOnly]
        public ActionResult LastClassesPanel()
        {
            var classAccessRepository = new ClassAccessRepository(_context);
            return PartialView("_LastClassesPanel",
                ClassAccessViewModel.FromEntityList(classAccessRepository.ListLastAccesses(_loggedUser.Id),
                    new DefaultDateTimeHumanizeStrategy()));
        }

        [HttpPost]
        public ActionResult ListComments(Guid classId, int page = 1)
        {
            var classRepository = new ClassRepository(_context);
            var classInfo = classRepository.GetClass(classId, _loggedUser.Id, GetUserRole(_loggedUser));
            var humanizer = new DefaultDateTimeHumanizeStrategy();
            var comments = classInfo.Class.Comments
                .OrderByDescending(x => x.DateTime)
                .Skip((page - 1) * 10)
                .Take(10)
                .ToList();

            return Json(CommentViewModel.FromEntityList(comments, humanizer, _loggedUser.Id),
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Comment(FormCollection formData)
        {
            if (string.IsNullOrEmpty(formData["CommentText"]))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);


            var comment = new CommentViewModel
            {
                ClassId = new Guid(formData["ClassId"]),
                CommentText = formData["CommentText"]
            };

            var classRepository = new ClassRepository(_context);
            var classInfo = classRepository.GetClass(comment.ClassId, _loggedUser.Id, GetUserRole(_loggedUser));
            comment.DateTime = DateTime.Now;
            classRepository.SendComment(comment.ToEntity(_loggedUser, classInfo.Class));
            _context.Save(_loggedUser);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult DeleteComment(long commentId)
        {
            var classRepository = new ClassRepository(_context);
            classRepository.DeleteComment(commentId);
            _context.Save(_loggedUser);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [AllowAnonymous]
        public ActionResult Download(Guid id)
        {
            var classRepository = new ClassRepository(_context);
            var file = classRepository.GetFile(id);

            var classAvailable = classRepository.CheckClassAvailability(file.Class.Id, _loggedUser?.Id);
            if (classAvailable)
            {
                classRepository.SaveAccess(file, _loggedUser);
                return File(Url.Content("~/" + Parameter.FILE_STORAGE + "/" + file.Class.Id + "/" + file.PhysicalPath),
                    "application/octet-stream", file.PhysicalPath);
            }

            TempData["MessageType"] = "error";
            TempData["MessageTitle"] = Resource.SupportMaterialDownloadToastrTitle;
            TempData["Message"] = Resource.WithoutPermissionDownloadToastrMessage;
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult IndexAdmin(string term, string searchFieldName, int page = 1)
        {
            ViewBag.SearchFields = new SelectList(new[] {"Name", "Subject", "Knowledge Area", "Course", "Id"});
            var classRepository = new ClassRepository(_context);
            return View(ClassViewModel.FromEntityList(classRepository.Search(term, searchFieldName, page)));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Search(string term, string searchFieldName, int page = 1)
        {
            var classRepository = new ClassRepository(_context);
            return Json(ClassViewModel.FromEntityList(classRepository.Search(term, searchFieldName, page)));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var courseRepository = new CourseRepository(_context);
            var activeCourses = courseRepository.ListActiveCourses();
            ViewBag.Courses = new SelectList(activeCourses, "Id", "Name");

            var userRepository = new UserRepository(_context);
            var activeTeachers = userRepository.ListActiveTeachers();
            ViewBag.Teachers = new SelectList(activeTeachers, "Id", "Name");
            const ContentType contentType = ContentType.Vimeo;

            ViewBag.ContentTypes = new SelectList(contentType.ToDataSource<ContentType>(), "Key", "Value");

            return View();
        }

        // POST: teacher/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create(ClassViewModel viewModel)
        {
            var courseRepository = new CourseRepository(_context);
            var userRepository = new UserRepository(_context);

            if (ModelState.IsValid)
                try
                {

SmartLMS.WebUI/Controllers/NoticeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Carubbi.Extensions;
using Carubbi.Utils.DataTypes;
using Humanizer.DateTimeHumanizeStrategy;
using SmartLMS.Domain;
using SmartLMS.Domain.Entities.Communication;
using SmartLMS.Domain.Repositories;
using SmartLMS.Domain.Services;
using SmartLMS.WebUI.Models;

namespace SmartLMS.WebUI.Controllers
{
    [Authorize]
    public class NoticeController : BaseController
    {
        public NoticeController(IContext context)
            : base(context)
        {
        }


        [ChildActionOnly]
        public ActionResult NoticePanel()
        {
            var repo = new NoticeRepository(_context);
            var notices = repo.ListNotSeenNotices(_loggedUser.Id);
            var dateTimeHumanizerStrategy = new DefaultDateTimeHumanizeStrategy();
            return PartialView("_NoticePanel", NoticeViewModel.FromEntityList(notices, dateTimeHumanizerStrategy));
        }

        [HttpPost]
        public ActionResult Visualize(long noticeId, Guid userId)
        {
            var noticeRepository = new NoticeRepository(_context);
            var notSeenNotices = noticeRepository.ListNotSeenNotices(userId);

            var userNotice = new UserNotice
            {
                VisualizationDateTime = DateTime.Now,
                NoticeId = noticeId,
                UserId = userId
            };
            _context.GetList<UserNotice>().Add(userNotice);
            _context.Save();

            var dateTimeHumanizerStrategy = new DefaultDateTimeHumanizeStrategy();
            var nextNotice = noticeRepository.ListNotSeenNotices(userId).Except(notSeenNotices).FirstOrDefault();
            if (nextNotice != null)
                return Json(NoticeViewModel.FromEntity(nextNotice, dateTimeHumanizerStrategy));

            return new EmptyResult();
        }

        public ActionResult Index()
        {
            const NoticeType notivceType = NoticeType.Public;
            ViewBag.NoticeTypes = new SelectList(notivceType.ToDataSource<NoticeType>(), "Key", "Value");
            var range = new DateRange
            {
                StartDate = DateTime.Now.AddMonths(-1),
                EndDate = DateTime.Now
            };
            var historyService = new HistoryService(_context, new DefaultDateTimeHumanizeStrategy());
            return View(
                NoticeViewModel.FromEntityList(historyService.SearchNotices(range, 1, _loggedUser.Id, NoticeType.All)));
        }

        public ActionResult Send()
        {
            const NoticeType notivceType = NoticeType.Public;
            ViewBag.NoticeTypes = new SelectList(notivceType.ToDataSource<NoticeType>(), "Key", "Value");
            return View();
        }

        public ActionResult ListNoticeHistory(DateTime? startDate, DateTime? endDate,
            NoticeType noticeType = NoticeType.All, int page = 1)
        {
            var range = new DateRange
            {
                StartDate = startDate,
                EndDate = endDate
            };

            var historyService = new HistoryService(_context, new DefaultDateTimeHumanizeStrategy());
            return Json(
                NoticeViewModel.FromEntityList(historyService.SearchNotices(range, page, _loggedUser.Id, noticeType)),
                JsonRequestBehavior.AllowGet);
        }
    }
}

SmartLMS.WebUI/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Carubbi.Extensions;
using Carubbi.Utils.DataTypes;
using Humanizer.DateTimeHumanizeStrategy;
using SmartLMS.Domain;
using SmartLMS.Domain.Repositories;
using SmartLMS.Domain.Services;
using SmartLMS.WebUI.Models;

namespace SmartLMS.WebUI.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        public UserController(IContext context)
            : base(context)
        {
        }

        [AllowAnonymous]
        [ChildActionOnly]
        public ActionResult Header()
        {
            var userRepository = new UserRepository(_context);
            var knowledgeAreaRepository = new KnowledgeAreaRepository(_context);
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var viewModel = new HeaderViewModel
                {
                    User = UserViewModel.FromEntity(userRepository.GetByLogin(HttpContext.User.Identity.Name)),
                    KnowledgeAreas = KnowledgeAreaViewModel
                        .FromEntityList(knowledgeAreaRepository.ListActiveKnowledgeAreas(), 2).ToList()
                };

                return PartialView($"_{viewModel.User.RoleName}Header", viewModel);
            }
            else
            {
                var viewModel = new HeaderViewModel
                {
                    KnowledgeAreas = KnowledgeAreaViewModel
                        .FromEntityList(knowledgeAreaRepository.ListActiveKnowledgeAreas(), 2).ToList()
                };
                return PartialView("_Login", viewModel);
            }
        }


        public ActionResult AccessHistory()
        {
            const AccessType accessType = AccessType.File;
            ViewBag.AccessTypes = new SelectList(accessType.ToDataSource<AccessType>(), "Key", "Value");

            var range = new DateRange
            {
                StartDate = DateTime.Now.AddMonths(-1),
                EndDate = DateTime.Now
            };

            var historyService = new HistoryService(_context, new DefaultDateTimeHumanizeStrategy());
            return View(
                AccessViewModel.FromEntityList(historyService.SearchAccess(range, 1, _loggedUser.Id, AccessType.All)));
        }


        public ActionResult ListAccessHistory(DateTime? startDate, DateTime? endDate,
            AccessType accessType = AccessType.All, int page = 1)
        {
            var range = new DateRange
            {
                StartDate = startDate,
                EndDate = endDate
            };

            var historyService = new HistoryService(_context, new DefaultDateTimeHumanizeStrategy());
            return Json(
                AccessViewModel.FromEntityList(historyService.SearchAccess(range, page, _loggedUser.Id, accessType)),
                JsonRequestBehavior.AllowGet);
        }
    }
}

SmartLMS.WebUI/Views/User/_AdminHeader.cshtml
@using SmartLMS.Domain.Entities
@using SmartLMS.Domain.Resources
@model HeaderViewModel
<nav class="navbar navbar-primary navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <div id="logo" class="img-circle img-raised navbar-brand">
                <img src="~/content/img/logo.png" width="40" height="40" alt="@Parameter.APP_NAME logo" rel="tooltip">
            </div>
            @Html.ActionLink(Parameter.APP_NAME, "Index", "Home", null, new {@class = "navbar-brand"})
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        @Resource.ManagementAdminMenuItem <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">@Resource.PeopleManagementSection</li>
                        <li>@Html.ActionLink(Resource.StudentAdminMenuItem, "IndexAdmin", "Student")</li>
                        <li>@Html.ActionLink(Resource.TeacherAdminMenuItem, "IndexAdmin", "Teacher")</li>
                        <li>@Html.ActionLink(Resource.ClassroomAdminMenuItem, "IndexAdmin", "ClassRoom")</li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">@Resource.ContentManagementSection</li>
                        <li>@Html.ActionLink(Resource.KnowledgeAreaPlural, "IndexAdmin", "KnowledgeArea")</li>
                        <li>@Html.ActionLink(Resource.SubjectPlural, "IndexAdmin", "Subject")</li>
                        <li>@Html.ActionLink(Resource.CoursePlural, "IndexAdmin", "Course")</li>
                        <li>@Html.ActionLink(Resource.ClassPlural, "IndexAdmin", "Class")</li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Send", "Notice")">@Resource.SendNoticeMenuItem</a>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#talk-to-us">@Resource.TalkToUsMenuItem</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        @Resource.ChangeLanguageMenuItem <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Português (Brasil)", "ChangeLanguage", "Home", new { culture = "pt-BR" }, null)</li>
                        <li>@Html.ActionLink("English (UK)", "ChangeLanguage", "Home", new { culture = "en-UK" }, null)</li>
                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#about">@Resource.AboutMenuItem</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>@Model.User.Name <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("Index", "Notice")">@Resource.NoticeMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("AccessHistory", "User")">@Resource.AccessHistoryMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ChangePassword", "Authentication")">@Resource.ChangePasswordMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Signout", "Authentication")">@Resource.LogoutMenuItem</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

SmartLMS.WebUI/Views/User/_StudentHeader.cshtml
@using SmartLMS.Domain.Entities
@using SmartLMS.Domain.Resources
@model HeaderViewModel
<nav class="navbar navbar-primary navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <div id="logo" class="img-circle img-raised navbar-brand">
                <img src="~/content/img/logo.png" width="40" height="40" alt="@Parameter.APP_NAME logo" rel="tooltip">
            </div>
            @Html.ActionLink(Parameter.APP_NAME, "Index", "Home", null, new {@class = "navbar-brand"})
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        @Resource.KnowledgeAreaPlural
                        <b class="caret"></b>
                        <div class="ripple-container"></div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        @foreach (var item in Model.KnowledgeAreas)
                        {
                            <li>
                                <a href="@Url.Action("Index", "Subject", new {item.Id})">@item.Name</a>
                            </li>
                        }
                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#talk-to-us">@Resource.TalkToUsMenuItem</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        @Resource.ChangeLanguageMenuItem <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Português (Brasil)", "ChangeLanguage", "Home", new {culture = "pt-BR"}, null)</li>
                        <li>@Html.ActionLink("English (UK)", "ChangeLanguage", "Home", new {culture = "en-UK"}, null)</li>
                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#about">@Resource.AboutMenuItem</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>@Model.User.Name<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("Index", "Notice")">@Resource.NoticeMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("AccessHistory", "User")">@Resource.AccessHistoryMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ChangePassword", "Authentication")">@Resource.ChangePasswordMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Signout", "Authentication")">@Resource.LogoutMenuItem</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

SmartLMS.WebUI/Views/User/_TeacherHeader.cshtml
@using SmartLMS.Domain.Entities
@using SmartLMS.Domain.Resources
@model HeaderViewModel
<nav class="navbar navbar-primary navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <div id="logo" class="img-circle img-raised navbar-brand">
                <img src="~/content/img/logo.png" width="40" height="40" alt="@Parameter.APP_NAME logo" rel="tooltip">
            </div>
            @Html.ActionLink(Parameter.APP_NAME, "Index", "Home", null, new {@class = "navbar-brand"})
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        @Resource.KnowledgeAreaPlural
                        <b class="caret"></b>
                        <div class="ripple-container"></div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        @foreach (var item in Model.KnowledgeAreas)
                        {
                            <li>
                                <a href="@Url.Action("Index", "Subject", new {item.Id})">@item.Name</a>
                            </li>
                        }
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Management <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("Index", "Classroom")">@Resource.ClassroomsMenuItem</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">@Resource.MonitoringMenuSectionMenuDivider</li>
                        <li>
                            <a href="@Url.Action("StudentsAccessHistory", "Teacher")">@Resource.StudentAccessMenuItem</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#talk-to-us">@Resource.TalkToUsMenuItem</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        @Resource.ChangeLanguageMenuItem <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Português (Brasil)", "ChangeLanguage", "Home", new {culture = "pt-BR"}, null)</li>
                        <li>@Html.ActionLink("English (UK)", "ChangeLanguage", "Home", new {culture = "en-UK"}, null)</li>
                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#about">@Resource.AboutMenuItem</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>@Model.User.Name <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("Index", "Notice")">@Resource.NoticeMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("AccessHistory", "User")">@Resource.AccessHistoryMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ChangePassword", "Authentication")">@Resource.ChangePasswordMenuItem</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Signout", "Authentication")">@Resource.LogoutMenuItem</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>